# Generated by Django 5.2.9 on 2025-12-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=150)),
                ('prod_price', models.IntegerField()),
                ('prod_quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
