# Generated by Django 5.2.9 on 2025-12-20 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=150, unique=True)),
                ('showtime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('screename', models.CharField(max_length=150)),
                ('dataandtime', models.DateTimeField(auto_now_add=True)),
                ('trasactionid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
