# Generated by Django 5.2.9 on 2025-12-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_movieticketbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieticketbooking',
            name='moviename',
            field=models.CharField(max_length=150),
        ),
    ]
