# Generated by Django 5.2.9 on 2025-12-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_alter_movieticketbooking_moviename'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('authorName', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
