# Generated by Django 5.2.9 on 2025-12-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_courseregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieticketbooking',
            name='genres',
            field=models.CharField(default='Action', max_length=100),
        ),
    ]
