# Generated by Django 5.2.9 on 2025-12-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_movieticketbooking_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieticketbooking',
            old_name='screename',
            new_name='screenname',
        ),
    ]
