# Generated by Django 5.2.9 on 2025-12-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_rename_screename_movieticketbooking_screenname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('bookprice', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('book_type', models.CharField(max_length=100)),
            ],
        ),
    ]
