# Generated by Django 5.2.9 on 2026-01-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_bookdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
