# Generated by Django 5.2.9 on 2026-01-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('python_marks', models.IntegerField()),
                ('django_marks', models.IntegerField()),
                ('sql_marks', models.IntegerField()),
                ('total', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
    ]
